a=str(input("Kelimeyi Girin:\n"))
a=a.upper()
a=a.replace("0", "SIFIR")
a=a.replace("1", "BİR")
a=a.replace("2", "İKİ")
a=a.replace("3", "ÜÇ")
a=a.replace("4", "DÖRT")
a=a.replace("5", "BEŞ")
a=a.replace("6", "ALTI")
a=a.replace("7", "YEDİ")
a=a.replace("8", "SEKİZ")
a=a.replace("9", "DOKUZ")
a=" ".join(a)
print(a)
